var SUPABASE_URL='https://tkuivkhghmeljcuqwwdy.supabase.co';
var SUPABASE_KEY='sb_publishable_pBOO7h7_TBtfDhv_vYqEFw_MCpHFkq-';
var TABLE='2026';
var rows=[];var filtered=[];var page=1;var pageSize=20;
function el(id){return document.getElementById(id)}
function txt(v){return (v===null||v===undefined)?'':String(v).trim()}
function low(v){return txt(v).toLowerCase()}
function fmt(n){return Number(n||0).toLocaleString()}
function pct(n,d){return d?((n/d)*100).toFixed(1):'0.0'}
function label(v){return txt(v).replace(/-/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase()})||'None'}
function badge(v){var x=txt(v)||'none';var c='';if(['will-vote','called','reach','reached','guaranteed'].indexOf(x)>-1)c='ok';if(['need-call','not-decided','not-visited','need-transport','busy','not-answer'].indexOf(x)>-1)c='warn';if(['not-vote','disconnected','wrong-number','out-of-coverage'].indexOf(x)>-1)c='danger';return '<span class="badge '+c+'">'+label(x)+'</span>'}
function norm(r){r.vote_status=r.vote_status||'not-decided';r.phone_status=r.phone_status||'need-call';r.d2d_status=r.d2d_status||'not-visited';r.reach_status=r.reach_status||'not-reached';r.support_level=r.support_level||'normal';r.transport_status=r.transport_status||'not-needed';return r}
async function getBatch(from,to){var url=SUPABASE_URL+'/rest/v1/'+encodeURIComponent(TABLE)+'?select=*&order=id.asc';var res=await fetch(url,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,Range:from+'-'+to,'Range-Unit':'items'}});if(!res.ok){throw new Error('Supabase '+res.status+': '+await res.text())}return await res.json()}
async function load(){try{el('connectionStatus').textContent='Loading… 0';var all=[];var from=0;var size=1000;while(true){var batch=await getBatch(from,from+size-1);all=all.concat(batch);el('connectionStatus').textContent='Loading… '+fmt(all.length);if(batch.length<size)break;from+=size}rows=all.map(norm);el('connectionStatus').textContent='Connected • '+fmt(rows.length)+' records';el('lastUpdated').textContent=new Date().toLocaleString();page=1;render()}catch(e){console.error(e);el('connectionStatus').textContent='Load error';document.body.insertAdjacentHTML('afterbegin','<div style="background:#fee;color:#900;padding:12px;font-weight:700">'+String(e.message||e)+'</div>')}}
function metrics(list){list=list||rows;var total=list.length;var reached=0,called=0,willVote=0,needCall=0,assigned=0,notDecided=0,needTransport=0,d2d=0,guaranteed=0;list.forEach(function(r){if(r.reach_status==='reached'||r.vote_status==='will-vote'||r.vote_status==='not-vote'||r.phone_status==='called'||r.d2d_status==='reach')reached++;if(r.phone_status==='called')called++;if(r.vote_status==='will-vote')willVote++;if(r.phone_status==='need-call'||!r.phone_status)needCall++;if(txt(r.vote_assigned_by))assigned++;if(r.vote_status==='not-decided'||!r.vote_status)notDecided++;if(r.transport_status==='need-transport')needTransport++;if(r.d2d_status==='reach')d2d++;if(r.support_level==='guaranteed')guaranteed++});return{total:total,reached:reached,called:called,willVote:willVote,needCall:needCall,assigned:assigned,unassigned:total-assigned,notDecided:notDecided,needTransport:needTransport,d2d:d2d,guaranteed:guaranteed}}
function applyFilter(){var q=low(el('searchInput').value);var party=el('partyFilter').value;var status=el('statusFilter').value;pageSize=Number(el('pageSize').value||20);filtered=rows.filter(function(r){var hay=[r.name,r.national_id,r.phone,r.house,r.lives_in,r.living_place,r.party,r.remarks,r.vote_assigned_by].map(low).join(' ');if(q&&hay.indexOf(q)===-1)return false;if(party!=='all'&&txt(r.party).toUpperCase()!==party)return false;if(status==='unassigned')return !txt(r.vote_assigned_by);if(status!=='all')return [r.vote_status,r.phone_status,r.d2d_status,r.reach_status,r.transport_status,r.support_level].indexOf(status)>-1;return true});filtered.sort(function(a,b){return txt(a.house).localeCompare(txt(b.house))||txt(a.name).localeCompare(txt(b.name))})}
function render(){applyFilter();renderKpis();renderProgress();renderPriorities();renderRecords();renderAnalytics();renderReport()}
function renderKpis(){var m=metrics(rows);var a=[['Total Records',m.total,'All voters in table'],['Reached',m.reached,pct(m.reached,m.total)+'% outreach'],['Called',m.called,pct(m.called,m.total)+'% phone'],['Will Vote',m.willVote,pct(m.willVote,m.total)+'% support'],['Need Call',m.needCall,pct(m.needCall,m.total)+'% pending'],['Assigned',m.assigned,fmt(m.unassigned)+' unassigned']];el('kpiGrid').innerHTML=a.map(function(x){return '<article class="kpi"><span>'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><small>'+x[2]+'</small></article>'}).join('')}
function renderProgress(){var m=metrics(rows);var a=[['Reach rate',m.reached,m.total],['Call rate',m.called,m.total],['Will vote rate',m.willVote,m.total],['D2D reach',m.d2d,m.total],['Guaranteed',m.guaranteed,m.total]];el('progressBars').innerHTML=a.map(function(x){var p=pct(x[1],x[2]);return '<div class="progress-item"><div class="progress-top"><span>'+x[0]+'</span><span>'+p+'%</span></div><div class="bar"><i style="width:'+Math.min(Number(p),100)+'%"></i></div><small>'+fmt(x[1])+' of '+fmt(x[2])+'</small></div>'}).join('')}
function renderPriorities(){var m=metrics(rows);el('priorityList').innerHTML=[['Need call',m.needCall],['Not decided',m.notDecided],['Unassigned',m.unassigned],['Need transport',m.needTransport]].map(function(x){return '<div class="priority"><b>'+x[0]+'</b><strong>'+fmt(x[1])+'</strong></div>'}).join('')}
function renderRecords(){var pages=Math.max(1,Math.ceil(filtered.length/pageSize));if(page>pages)page=pages;var start=(page-1)*pageSize;var list=filtered.slice(start,start+pageSize);el('recordCount').textContent=fmt(filtered.length)+' records';el('pageInfo').textContent='Page '+page+' of '+pages;el('prevPage').disabled=page<=1;el('nextPage').disabled=page>=pages;el('recordsBody').innerHTML=list.map(function(r){var phone=txt(r.phone);return '<tr><td><div class="person"><span class="avatar"></span><div><b>'+ (txt(r.name)||'No name') +'</b><br><small>'+ (txt(r.national_id)||'No ID') +'</small></div></div></td><td>'+ (txt(r.house)||'-') +'</td><td>'+ (phone?'<a href="tel:'+phone+'">'+phone+'</a>':'-') +'</td><td>'+badge(r.party)+'</td><td>'+badge(r.vote_status)+'</td><td>'+badge(r.phone_status)+'</td><td>'+badge(r.d2d_status)+'</td><td>'+ (txt(r.vote_assigned_by)||'<span class="badge warn">Unassigned</span>') +'</td><td><button class="primary" disabled>View</button></td></tr>'}).join('')||'<tr><td colspan="9">No records found.</td></tr>'}
function renderAnalytics(){var groups={};rows.forEach(function(r){var k=txt(r.party).toUpperCase()||'UNKNOWN';if(!groups[k])groups[k]=[];groups[k].push(r)});el('partyAnalytics').innerHTML=Object.keys(groups).map(function(k){var mm=metrics(groups[k]);return '<div class="analytics-row"><div><b>'+k+'</b><br><small>'+fmt(groups[k].length)+' records</small></div><div><b>'+pct(mm.willVote,mm.total)+'%</b><br><small>will vote</small></div><div><b>'+pct(mm.reached,mm.total)+'%</b><br><small>reached</small></div></div>'}).join('');el('insightsList').innerHTML='<div class="insight"><b>Loaded full database</b><br><small>'+fmt(rows.length)+' records included.</small></div>'}
function renderReport(){var m=metrics(rows);el('reportOutput').textContent='Report\nTotal records: '+fmt(m.total)+'\nReached: '+fmt(m.reached)+'\nCalled: '+fmt(m.called)+'\nWill vote: '+fmt(m.willVote)+'\nNeed call: '+fmt(m.needCall)+'\nAssigned: '+fmt(m.assigned)+'\nUnassigned: '+fmt(m.unassigned)}
function exportCsv(){var list=filtered.length?filtered:rows;var cols=['id','name','national_id','house','phone','party','vote_status','phone_status','d2d_status','reach_status','vote_assigned_by'];var csv=[cols.join(',')].concat(list.map(function(r){return cols.map(function(c){return '"'+txt(r[c]).replace(/"/g,'""')+'"'}).join(',')})).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='campaign-export.csv';a.click()}
document.addEventListener('DOMContentLoaded',function(){['searchInput','partyFilter','statusFilter','pageSize'].forEach(function(id){el(id).addEventListener('input',function(){page=1;render()})});el('prevPage').onclick=function(){if(page>1){page--;renderRecords()}};el('nextPage').onclick=function(){page++;renderRecords()};el('refreshBtn').onclick=load;el('exportBtn').onclick=exportCsv;el('copyReportBtn').onclick=function(){navigator.clipboard.writeText(el('reportOutput').textContent)};document.addEventListener('click',function(e){var b=e.target.closest('[data-view]');if(b){document.querySelectorAll('.nav-btn').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active')});el(b.dataset.view+'View').classList.add('active')}});load()});
