const SUPABASE_URL='https://tkuivkhghmeljcuqwwdy.supabase.co';
const SUPABASE_KEY='sb_publishable_pBOO7h7_TBtfDhv_vYqEFw_MCpHFkq-';
const TABLE='2026';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const state={rows:[],filtered:[],page:1,pageSize:20};
const $=id=>document.getElementById(id);
const s=v=>(v??'').toString().trim();
const low=v=>s(v).toLowerCase();
const fmt=n=>Number(n||0).toLocaleString();
const pct=(n,d)=>d?((n/d)*100).toFixed(1):'0.0';
function title(v){return s(v).replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())||'None'}
function tag(v){let x=s(v)||'none',c='';if(['will-vote','called','reach','reached','guaranteed'].includes(x))c='ok';if(['need-call','not-decided','not-visited','need-transport','busy','not-answer'].includes(x))c='warn';if(['not-vote','disconnected','wrong-number','out-of-coverage'].includes(x))c='danger';return `<span class="badge ${c}">${title(x)}</span>`}
function norm(r){return {...r,vote_status:r.vote_status||'not-decided',phone_status:r.phone_status||'need-call',d2d_status:r.d2d_status||'not-visited',reach_status:r.reach_status||'not-reached',support_level:r.support_level||'normal',transport_status:r.transport_status||'not-needed'}}
async function fetchAll(){let all=[],from=0,size=1000;while(true){$('connectionStatus').textContent=`Loading… ${fmt(all.length)}`;let {data,error}=await db.from(TABLE).select('*').order('id',{ascending:true}).range(from,from+size-1);if(error)throw error;let batch=data||[];all=all.concat(batch);if(batch.length<size)break;from+=size}return all}
function m(rows=state.rows){let total=rows.length,reached=rows.filter(r=>r.reach_status==='reached'||['will-vote','not-vote'].includes(r.vote_status)||r.phone_status==='called'||r.d2d_status==='reach').length,called=rows.filter(r=>r.phone_status==='called').length,willVote=rows.filter(r=>r.vote_status==='will-vote').length,needCall=rows.filter(r=>r.phone_status==='need-call'||!r.phone_status).length,assigned=rows.filter(r=>s(r.vote_assigned_by)).length,notDecided=rows.filter(r=>r.vote_status==='not-decided'||!r.vote_status).length,needTransport=rows.filter(r=>r.transport_status==='need-transport').length,d2d=rows.filter(r=>r.d2d_status==='reach').length,guaranteed=rows.filter(r=>r.support_level==='guaranteed').length;return{total,reached,called,willVote,needCall,assigned,unassigned:total-assigned,notDecided,needTransport,d2d,guaranteed}}
function filter(){let q=low($('searchInput').value),party=$('partyFilter').value,status=$('statusFilter').value;state.pageSize=Number($('pageSize').value||20);state.filtered=state.rows.filter(r=>{let hay=[r.name,r.national_id,r.phone,r.house,r.lives_in,r.living_place,r.party,r.remarks,r.vote_assigned_by].map(low).join(' ');if(q&&!hay.includes(q))return false;if(party!=='all'&&s(r.party).toUpperCase()!==party)return false;if(status==='unassigned')return !s(r.vote_assigned_by);if(status!=='all')return[r.vote_status,r.phone_status,r.d2d_status,r.reach_status,r.transport_status,r.support_level].includes(status);return true}).sort((a,b)=>s(a.house).localeCompare(s(b.house))||s(a.name).localeCompare(s(b.name)))}
function kpis(){let x=m();let arr=[['Total Records',x.total,'All voters in table'],['Reached',x.reached,`${pct(x.reached,x.total)}% outreach`],['Called',x.called,`${pct(x.called,x.total)}% phone`],['Will Vote',x.willVote,`${pct(x.willVote,x.total)}% support`],['Need Call',x.needCall,`${pct(x.needCall,x.total)}% pending`],['Assigned',x.assigned,`${fmt(x.unassigned)} unassigned`]];$('kpiGrid').innerHTML=arr.map(a=>`<article class="kpi"><span>${a[0]}</span><strong>${fmt(a[1])}</strong><small>${a[2]}</small></article>`).join('')}
function progress(){let x=m();let arr=[['Reach rate',x.reached,x.total],['Call rate',x.called,x.total],['Will vote rate',x.willVote,x.total],['D2D reach',x.d2d,x.total],['Guaranteed',x.guaranteed,x.total]];$('progressBars').innerHTML=arr.map(a=>{let p=pct(a[1],a[2]);return`<div class="progress-item"><div class="progress-top"><span>${a[0]}</span><span>${p}%</span></div><div class="bar"><i style="width:${Math.min(Number(p),100)}%"></i></div><small>${fmt(a[1])} of ${fmt(a[2])}</small></div>`}).join('')}
function priorities(){let x=m();$('priorityList').innerHTML=[['Need call',x.needCall],['Not decided',x.notDecided],['Unassigned',x.unassigned],['Need transport',x.needTransport]].map(a=>`<div class="priority"><b>${a[0]}</b><strong>${fmt(a[1])}</strong></div>`).join('')}
function records(){let pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));if(state.page>pages)state.page=pages;let start=(state.page-1)*state.pageSize,rows=state.filtered.slice(start,start+state.pageSize);$('recordCount').textContent=`${fmt(state.filtered.length)} records`;$('pageInfo').textContent=`Page ${state.page} of ${pages}`;$('prevPage').disabled=state.page<=1;$('nextPage').disabled=state.page>=pages;$('recordsBody').innerHTML=rows.map(r=>`<tr><td><div class="person"><span class="avatar"></span><div><b>${s(r.name)||'No name'}</b><br><small>${s(r.national_id)||'No ID'}</small></div></div></td><td>${s(r.house)||'-'}</td><td>${s(r.phone)?`<a href="tel:${s(r.phone)}">${s(r.phone)}</a>`:'-'}</td><td>${tag(r.party)}</td><td>${tag(r.vote_status)}</td><td>${tag(r.phone_status)}</td><td>${tag(r.d2d_status)}</td><td>${s(r.vote_assigned_by)||'<span class="badge warn">Unassigned</span>'}</td><td><button class="primary" disabled>View</button></td></tr>`).join('')||'<tr><td colspan="9">No records found.</td></tr>'}
function analytics(){let groups={};state.rows.forEach(r=>{let k=s(r.party).toUpperCase()||'UNKNOWN';(groups[k]??=[]).push(r)});$('partyAnalytics').innerHTML=Object.entries(groups).map(([p,rows])=>{let x=m(rows);return`<div class="analytics-row"><div><b>${p}</b><br><small>${fmt(rows.length)} records</small></div><div><b>${pct(x.willVote,x.total)}%</b><br><small>will vote</small></div><div><b>${pct(x.reached,x.total)}%</b><br><small>reached</small></div></div>`}).join('');let x=m();$('insightsList').innerHTML=`<div class="insight"><b>Loaded full database</b><br><small>${fmt(x.total)} records are included in all dashboard counts.</small></div>`}
function report(){let x=m();$('reportOutput').textContent=`Report\nTotal records: ${fmt(x.total)}\nReached: ${fmt(x.reached)}\nCalled: ${fmt(x.called)}\nWill vote: ${fmt(x.willVote)}\nNeed call: ${fmt(x.needCall)}\nAssigned: ${fmt(x.assigned)}\nUnassigned: ${fmt(x.unassigned)}`}
function render(){filter();kpis();progress();priorities();records();analytics();report()}
async function load(){try{state.rows=(await fetchAll()).map(norm);$('connectionStatus').textContent=`Connected • ${fmt(state.rows.length)} records`;$('lastUpdated').textContent=new Date().toLocaleString();state.page=1;render()}catch(e){console.error(e);$('connectionStatus').textContent='Connection error';alert(e.message||'Load failed')}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b){document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${b.dataset.view}View`).classList.add('active')}});
['searchInput','partyFilter','statusFilter','pageSize'].forEach(id=>$(id).addEventListener('input',()=>{state.page=1;render()}));
$('prevPage').onclick=()=>{if(state.page>1){state.page--;records()}};$('nextPage').onclick=()=>{state.page++;records()};$('refreshBtn').onclick=load;$('exportBtn').onclick=()=>{let rows=state.filtered.length?state.filtered:state.rows,cols=['id','name','national_id','house','phone','party','vote_status','phone_status','d2d_status','reach_status','vote_assigned_by'];let csv=[cols.join(',')].concat(rows.map(r=>cols.map(c=>'"'+s(r[c]).replaceAll('"','""')+'"').join(','))).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='export.csv';a.click()};$('copyReportBtn').onclick=async()=>navigator.clipboard.writeText($('reportOutput').textContent);
load();
