/* MODULE: Campaign Admin Core | VERSION: 20.0.0 | BUILD: 2026.07.10-clean-stable */
(() => {
'use strict';
const cfg=window.CampaignConfig, SECTIONS=['dashboard','residents','assign','calls','votes','visits','transport'];
const state={section:'dashboard',party:'all',search:'',filters:{},visible:28,rows:[],assignments:[],residentView:'gallery',user:null};
let db;
const text=v=>String(v??'').trim(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const addr=r=>text(r.house)||'No Address', living=r=>text(r.living_place)||text(r.lives_in)||'Not recorded';
const vote=r=>text(r.vote_status)||'not-decided', call=r=>text(r.call_outcome)||text(r.phone_status)||'need-call';
const visit=r=>text(r.d2d_status)||'not-visited', transport=r=>text(r.transport_status)||'not-needed';
const assign=r=>!text(r.vote_assigned_by)?'unassigned':text(r.reach_status)==='reached'?'completed':'assigned';
const cls=v=>'status-'+text(v||'none').toLowerCase().replace(/[^a-z0-9]+/g,'-');
const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-GB')};
const partyKey=v=>{v=text(v).toUpperCase();return v==='PNC'?'PNC':v==='MDP'?'MDP':'NONE'};
const config={
residents:{title:'Residents',stats:['Total','PNC','MDP','With Phone'],filters:['address','sex']},
assign:{title:'Assign',stats:['Total','Unassigned','Assigned','Completed'],filters:['address','assignStatus','assigner']},
calls:{title:'Calls',stats:['Total','Connected','Not Reached','Follow-up'],filters:['address','callStatus','callAgent']},
votes:{title:'Votes',stats:['Total','Will Vote','Not Vote','Not Decided'],filters:['address','voteStatus']},
visits:{title:'Door to Door',stats:['Total','Reached','Not Home','Not Visited'],filters:['address','visitStatus']},
transport:{title:'Transport',stats:['Total','Need Transport','Arranged','Not Needed'],filters:['address','transportStatus']}
};

function counts(){const c={all:state.rows.length,PNC:0,MDP:0,NONE:0};state.rows.forEach(r=>c[partyKey(r.party)]++);return c}
function login(message=''){
adminApp.innerHTML=`<main class="login-screen"><form id="loginForm" class="login-card"><div class="login-logo">2026</div><h1>Campaign Manager</h1>${message?`<div class="login-error">${esc(message)}</div>`:''}<label>Email<input id="email" type="email" value="${esc(localStorage.getItem('campaign_admin_email')||cfg.adminEmail||'')}" required></label><label>Password<input id="password" type="password" required></label><button class="btn primary">Sign In</button></form></main>`;
loginForm.onsubmit=async e=>{e.preventDefault();const mail=email.value.trim();localStorage.setItem('campaign_admin_email',mail);const{data,error}=await db.auth.signInWithPassword({email:mail,password:password.value});if(error)return login(error.message);state.user=data.user;loadAll()}
}
async function loadRows(){const rows=[];let from=0,size=Number(cfg.batchSize||1000);while(true){const{data,error}=await db.from(cfg.tableName).select('*').order('house',{ascending:true,nullsFirst:false}).order('id',{ascending:true}).range(from,from+size-1);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<size)break;from+=size}return rows}
async function loadAssignments(){const{data,error}=await db.from('resident_assignments').select('resident_id,assignee_name,assigned_at').order('assigned_at',{ascending:false});return error?[]:(data||[])}
async function loadAll(){adminApp.innerHTML='<main class="loading-screen"><div class="loading-box">Loading campaign data…</div></main>';try{[state.rows,state.assignments]=await Promise.all([loadRows(),loadAssignments()]);buildShell();const hash=location.hash.slice(1);if(SECTIONS.includes(hash))state.section=hash;applyPending();render()}catch(error){adminApp.innerHTML=`<main class="loading-screen"><div class="login-card"><h1>Database Load Error</h1><p>${esc(error.message)}</p><button id="retry" class="btn primary">Retry</button></div></main>`;retry.onclick=loadAll}}
function buildShell(){const c=counts();adminApp.innerHTML=`<div class="app-shell"><header class="topbar"><div class="topbar-main"><div class="brand"><span class="brand-mark">2026</span><span><strong>Campaign Manager</strong><small>Admin workspace</small></span></div><div class="status-wrap"><span class="status-dot"></span><span>${state.rows.length.toLocaleString()} records</span><button id="logoutButton" class="logout-button">Logout</button></div></div><div class="nav-row"><nav class="nav">${SECTIONS.map(s=>`<button data-section="${s}">${s[0].toUpperCase()+s.slice(1)}</button>`).join('')}</nav><label class="party-filter">Party<select id="globalParty"><option value="all">All (${c.all.toLocaleString()})</option><option value="PNC">PNC (${c.PNC.toLocaleString()})</option><option value="MDP">MDP (${c.MDP.toLocaleString()})</option><option value="NONE">No Party (${c.NONE.toLocaleString()})</option></select></label></div></header><main class="page"><section id="pageContent"></section></main></div>`;logoutButton.onclick=async()=>{await db.auth.signOut();state.rows=[];state.assignments=[];login()}}
function applyParty(rows){return state.party==='all'?rows:rows.filter(r=>partyKey(r.party)===state.party)}
function filtered(section){let rows=applyParty(state.rows.slice()),f=state.filters;if(state.search){const q=state.search.toLowerCase();rows=rows.filter(r=>[r.name,r.national_id,r.phone,addr(r),living(r),r.sex,r.age,r.party].map(text).join(' ').toLowerCase().includes(q))}if(f.address&&f.address!=='all')rows=rows.filter(r=>addr(r)===f.address);if(section==='residents'&&f.sex&&f.sex!=='all')rows=rows.filter(r=>text(r.sex).toLowerCase()===f.sex);if(section==='assign'){if(f.assignStatus&&f.assignStatus!=='all')rows=rows.filter(r=>assign(r)===f.assignStatus);if(f.assigner&&f.assigner!=='all'){const ids=new Set(state.assignments.filter(a=>text(a.assignee_name)===f.assigner).map(a=>String(a.resident_id)));rows=rows.filter(r=>ids.has(String(r.id)))}}if(section==='calls'){if(f.callStatus&&f.callStatus!=='all')rows=rows.filter(r=>call(r)===f.callStatus);if(f.callAgent&&f.callAgent!=='all')rows=rows.filter(r=>text(r.call_center_agent)===f.callAgent)}if(section==='votes'&&f.voteStatus&&f.voteStatus!=='all')rows=rows.filter(r=>vote(r)===f.voteStatus);if(section==='visits'&&f.visitStatus&&f.visitStatus!=='all')rows=rows.filter(r=>visit(r)===f.visitStatus);if(section==='transport'&&f.transportStatus&&f.transportStatus!=='all')rows=rows.filter(r=>transport(r)===f.transportStatus);return rows}
function select(name,opts){return`<select data-filter="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${state.filters[name]===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`}
function filterBar(section){const fs=config[section].filters,addresses=[...new Set(state.rows.map(addr))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),assigners=[...new Set(state.assignments.map(a=>text(a.assignee_name)).filter(Boolean))].sort(),agents=[...new Set(state.rows.map(r=>text(r.call_center_agent)).filter(Boolean))].sort();let h='<div class="filter-bar">';if(fs.includes('address'))h+=`<label>Official Address${select('address',[['all','All Addresses'],...addresses.map(v=>[v,v])])}</label>`;if(fs.includes('sex'))h+=`<label>Sex${select('sex',[['all','All'],['male','Male'],['female','Female']])}</label>`;if(fs.includes('assignStatus'))h+=`<label>Assign Status${select('assignStatus',[['all','All'],['unassigned','Unassigned'],['assigned','Assigned'],['completed','Completed']])}</label>`;if(fs.includes('assigner'))h+=`<label>Assigner${select('assigner',[['all','All Assigners'],...assigners.map(v=>[v,v])])}</label>`;if(fs.includes('callStatus'))h+=`<label>Call Status${select('callStatus',[['all','All'],['need-call','Need Call'],['connected','Connected'],['called','Called'],['busy','Busy'],['not-answer','Not Answer'],['wrong-number','Wrong Number'],['disconnected','Disconnected'],['out-of-coverage','Out of Coverage']])}</label>`;if(fs.includes('callAgent'))h+=`<label>Call Agent${select('callAgent',[['all','All Agents'],...agents.map(v=>[v,v])])}</label>`;if(fs.includes('voteStatus'))h+=`<label>Vote Status${select('voteStatus',[['all','All'],['will-vote','Will Vote'],['not-vote','Not Vote'],['not-decided','Not Decided']])}</label>`;if(fs.includes('visitStatus'))h+=`<label>Visit Status${select('visitStatus',[['all','All'],['reach','Reached'],['not-home','Not Home'],['live-in-another-place','Lives Elsewhere'],['not-visited','Not Visited']])}</label>`;if(fs.includes('transportStatus'))h+=`<label>Transport${select('transportStatus',[['all','All'],['need-transport','Need Transport'],['arranged','Arranged'],['picked-up','Picked Up'],['not-needed','Not Needed']])}</label>`;return h+`<label>Search<input id="searchInput" value="${esc(state.search)}" placeholder="Name, ID, phone, address or living place"></label><button id="clearFilters" class="btn secondary">Clear</button></div>`}
function statValues(section,rows){if(section==='residents')return[rows.length,rows.filter(r=>partyKey(r.party)==='PNC').length,rows.filter(r=>partyKey(r.party)==='MDP').length,rows.filter(r=>text(r.phone)).length];if(section==='assign')return[rows.length,rows.filter(r=>assign(r)==='unassigned').length,rows.filter(r=>assign(r)==='assigned').length,rows.filter(r=>assign(r)==='completed').length];if(section==='calls')return[rows.length,rows.filter(r=>['connected','called'].includes(call(r))).length,rows.filter(r=>['need-call','not-answer','wrong-number','disconnected','out-of-coverage'].includes(call(r))).length,rows.filter(r=>r.callback_scheduled_at).length];if(section==='votes')return[rows.length,rows.filter(r=>vote(r)==='will-vote').length,rows.filter(r=>vote(r)==='not-vote').length,rows.filter(r=>vote(r)==='not-decided').length];if(section==='visits')return[rows.length,rows.filter(r=>visit(r)==='reach').length,rows.filter(r=>visit(r)==='not-home').length,rows.filter(r=>visit(r)==='not-visited').length];return[rows.length,rows.filter(r=>transport(r)==='need-transport').length,rows.filter(r=>['arranged','picked-up'].includes(transport(r))).length,rows.filter(r=>transport(r)==='not-needed').length]}
function stats(section,rows){const v=statValues(section,rows);return`<div class="stats-grid">${config[section].stats.map((n,i)=>`<article class="stat-card"><span>${n}</span><strong>${v[i].toLocaleString()}</strong></article>`).join('')}</div>`}

function avatar(r,large=false){return text(r.photo_url)?`<img class="${large?'resident-photo':'avatar avatar-image'}" src="${esc(r.photo_url)}" alt="${esc(r.name||'Resident')}" loading="lazy">`:`<span class="${large?'resident-photo resident-photo-empty':'avatar'}">?</span>`}
function history(id){const items=state.assignments.filter(a=>String(a.resident_id)===String(id));return items.length?items.map(a=>`<span><strong>${esc(a.assignee_name)}</strong> · ${esc(fmt(a.assigned_at))}</span>`).join(''):'<span>Unassigned</span>'}
function editButton(section,r){return`<button class="btn primary" data-edit-id="${esc(r.id)}" data-edit-section="${section}">Edit</button>`}
function residentToolbar(){return`<div class="resident-view-toolbar"><strong>Resident View</strong><div class="view-toggle"><button data-resident-view="gallery" class="${state.residentView==='gallery'?'active':''}">Gallery</button><button data-resident-view="list" class="${state.residentView==='list'?'active':''}">List</button></div></div>`}
function loadMore(shown,rows){return`<div class="load-row"><button id="loadMore" class="btn secondary" ${shown.length>=rows.length?'disabled':''}>Load More</button><span>Showing ${shown.length.toLocaleString()} of ${rows.length.toLocaleString()}</span></div>`}
function residentGallery(rows){const shown=rows.slice(0,state.visible);return`${residentToolbar()}${filterBar('residents')}<div class="resident-gallery">${shown.map(r=>`<article class="resident-gallery-card">${avatar(r,true)}<div class="resident-gallery-body"><h3>${esc(r.name||'No name')}</h3><p class="resident-id">${esc(r.national_id||'No ID')}</p><dl><div><dt>Official Address</dt><dd>${esc(addr(r))}</dd></div><div><dt>Living Now</dt><dd>${esc(living(r))}</dd></div><div><dt>Mobile</dt><dd>${esc(r.phone||'Not recorded')}</dd></div><div><dt>Sex / Age</dt><dd>${esc(r.sex||'Not recorded')} · ${esc(r.age??'Not recorded')}</dd></div></dl>${editButton('residents',r)}</div></article>`).join('')||'<div class="empty-card">No residents found</div>'}</div>${loadMore(shown,rows)}`}
function residentList(rows){const shown=rows.slice(0,state.visible);return`${residentToolbar()}${filterBar('residents')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Photo</th><th>Name / ID</th><th>Official Address</th><th>Living Now</th><th>Mobile</th><th>Sex</th><th>Age</th><th>Action</th></tr></thead><tbody>${shown.map(r=>`<tr><td>${avatar(r)}</td><td><strong>${esc(r.name||'No name')}</strong><br><small>${esc(r.national_id||'No ID')}</small></td><td>${esc(addr(r))}</td><td>${esc(living(r))}</td><td>${esc(r.phone||'-')}</td><td>${esc(r.sex||'-')}</td><td>${esc(r.age??'-')}</td><td>${editButton('residents',r)}</td></tr>`).join('')||'<tr><td colspan="8">No residents found</td></tr>'}</tbody></table></div>${loadMore(shown,rows)}`}
function shareBar(){return`<div class="assignment-share-bar"><div><strong>Create self-assignment link</strong><small>Uses current party, address and search filters.</small></div><button id="copyAssignmentLink" class="btn primary">Generate Share Link</button></div>`}
function records(section,rows){
const shown=rows.slice(0,state.visible);
if(section==='residents')return state.residentView==='gallery'?residentGallery(rows):residentList(rows);
if(section==='visits')return`${filterBar(section)}<div class="cards-grid">${shown.map(r=>`<article class="record-card"><div class="card-header"><h4>${esc(r.name||'No name')}</h4><span class="status ${cls(visit(r))}">${esc(visit(r))}</span></div><div class="field"><span class="label">Resident ID</span><span class="value">${esc(r.national_id||'-')}</span></div><div class="field"><span class="label">Official Address</span><span class="value">${esc(addr(r))}</span></div><div class="field"><span class="label">Living Now</span><span class="value">${esc(living(r))}</span></div><div class="field"><span class="label">Phone</span><span class="value">${esc(r.phone||'-')}</span></div><div class="card-actions">${editButton(section,r)}</div></article>`).join('')||'<div class="empty-card">No records found</div>'}</div>${loadMore(shown,rows)}`;
const headers=section==='assign'?['Photo','Name / ID','Official Address','Phone','Assignees / Time','Status','Action']:section==='calls'?['Photo','Name','Official Address','Phone','Agent','Last Call','Status','Action']:section==='votes'?['Photo','Name','Official Address','Party','Status','Action']:['Photo','Name','Official Address','Phone','Status','Action'];
const body=shown.map(r=>{let c;if(section==='assign')c=[avatar(r),`<strong>${esc(r.name||'No name')}</strong><br><small>${esc(r.national_id||'No ID')}</small>`,esc(addr(r)),esc(r.phone||'-'),`<div class="assignment-history">${history(r.id)}</div>`,`<span class="status ${cls(assign(r))}">${esc(assign(r))}</span>`,editButton(section,r)];else if(section==='calls')c=[avatar(r),esc(r.name||'-'),esc(addr(r)),esc(r.phone||'-'),esc(r.call_center_agent||'-'),esc(fmt(r.last_call_at)),`<span class="status ${cls(call(r))}">${esc(call(r))}</span>`,editButton(section,r)];else if(section==='votes')c=[avatar(r),esc(r.name||'-'),esc(addr(r)),esc(r.party||'-'),`<span class="status ${cls(vote(r))}">${esc(vote(r))}</span>`,editButton(section,r)];else c=[avatar(r),esc(r.name||'-'),esc(addr(r)),esc(r.phone||'-'),`<span class="status ${cls(transport(r))}">${esc(transport(r))}</span>`,editButton(section,r)];return`<tr>${c.map(x=>`<td>${x}</td>`).join('')}</tr>`}).join('');
return`${filterBar(section)}${section==='assign'?shareBar():''}<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}">No records found</td></tr>`}</tbody></table></div>${loadMore(shown,rows)}`
}
function applyPending(){if(state.section!=='residents')return;const h=sessionStorage.getItem('campaign_prefilter_house');if(h){state.filters.address=h;sessionStorage.removeItem('campaign_prefilter_house')}}
function render(options={}){applyPending();document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===state.section));const p=document.getElementById('globalParty');if(p)p.value=state.party;if(state.section==='dashboard'){pageContent.innerHTML='<div class="md-loading">Loading campaign dashboard…</div>';document.dispatchEvent(new CustomEvent('campaign:dashboard'));return}const active=document.activeElement,restore=options.restoreSearch&&active?.id==='searchInput',start=restore?active.selectionStart:null,end=restore?active.selectionEnd:null;const rows=filtered(state.section);pageContent.innerHTML=`<section class="page-head"><div><p class="eyebrow">${config[state.section].title}</p><h1>${config[state.section].title}</h1></div><span class="record-pill">${rows.length.toLocaleString()} records</span></section>${stats(state.section,rows)}<section class="panel">${records(state.section,rows)}</section>`;if(restore){const input=document.getElementById('searchInput');if(input){input.focus({preventScroll:true});const len=input.value.length;input.setSelectionRange(Math.min(start??len,len),Math.min(end??len,len))}}}
function field(label,control,extra=''){return`<label class="editor-field ${extra}"><span>${label}</span>${control}</label>`}
function optionSelect(name,current,opts){return`<select name="${name}">${opts.map(([v,l])=>`<option value="${v}" ${String(v)===String(current)?'selected':''}>${l}</option>`).join('')}</select>`}
function readonly(label,value,name=''){return field(label,`<input ${name?`name="${name}"`:''} value="${esc(value||'')}" readonly class="readonly-input">`)}
function suggestion(r){return field('Suggested Phone Number',`<input name="phone_suggested" inputmode="tel" value="${esc(r.phone_suggested||'')}" placeholder="Write corrected number only">`,'compact-phone-suggestion')}
function openEditor(section,id){
const r=state.rows.find(x=>String(x.id)===String(id));if(!r)return;
let f=`<div class="locked-identity"><strong>${esc(r.name||'No name')}</strong><span>${esc(r.national_id||'No ID')} · ${esc(addr(r))}</span><small>Name, ID, official address, sex and age are locked.</small></div>`;
if(section==='residents')f+=field('Current Living Place',`<input name="living_place" value="${esc(living(r)==='Not recorded'?'':living(r))}">`)+field('Phone Number',`<input name="phone" value="${esc(r.phone||'')}">`)+field('Remarks',`<textarea name="remarks">${esc(r.remarks||'')}</textarea>`);
if(section==='assign')f+=readonly('Phone Number',r.phone)+readonly('Current Living Place',living(r))+field('Assign Status',optionSelect('assign_status',assign(r),[['unassigned','Unassigned'],['assigned','Assigned'],['completed','Completed']]))+field('Assigner',`<input name="vote_assigned_by" value="${esc(r.vote_assigned_by||'')}">`)+field('Remarks',`<textarea name="remarks">${esc(r.remarks||'')}</textarea>`)+suggestion(r);
if(section==='calls')f+=readonly('Phone Number',r.phone)+readonly('Current Living Place',living(r))+field('Call Status',optionSelect('phone_status',call(r),[['need-call','Need Call'],['connected','Connected'],['called','Called'],['busy','Busy'],['not-answer','Not Answer'],['wrong-number','Wrong Number'],['disconnected','Disconnected'],['out-of-coverage','Out of Coverage']]))+field('Agent',`<input name="call_center_agent" value="${esc(r.call_center_agent||'')}">`)+field('Notes',`<textarea name="call_notes">${esc(r.call_notes||'')}</textarea>`)+suggestion(r);
if(section==='votes')f+=readonly('Phone Number',r.phone)+readonly('Current Living Place',living(r))+field('Vote Status',optionSelect('vote_status',vote(r),[['not-decided','Not Decided'],['will-vote','Will Vote'],['not-vote','Not Vote']]))+field('Support',optionSelect('support_level',text(r.support_level)||'normal',[['normal','Normal'],['not-guaranteed','Not Guaranteed'],['guaranteed','Guaranteed']]))+field('Remarks',`<textarea name="remarks">${esc(r.remarks||'')}</textarea>`)+suggestion(r);
if(section==='visits')f+=readonly('Phone Number',r.phone)+field('Current Living Place',`<input name="living_place" value="${esc(living(r)==='Not recorded'?'':living(r))}">`)+field('Visit Status',optionSelect('d2d_status',visit(r),[['not-visited','Not Visited'],['reach','Reached'],['not-home','Not Home'],['live-in-another-place','Lives Elsewhere']]))+field('Remarks',`<textarea name="remarks">${esc(r.remarks||'')}</textarea>`)+suggestion(r);
if(section==='transport')f+=readonly('Phone Number',r.phone)+readonly('Current Living Place',living(r))+field('Transport Status',optionSelect('transport_status',transport(r),[['not-needed','Not Needed'],['need-transport','Need Transport'],['arranged','Arranged'],['picked-up','Picked Up']]))+field('Remarks',`<textarea name="remarks">${esc(r.remarks||'')}</textarea>`)+suggestion(r);
const m=document.createElement('div');m.className='editor-backdrop';m.id='sectionEditor';m.innerHTML=`<section class="editor-panel"><header class="editor-header"><div><p class="eyebrow">${config[section].title}</p><h2>${esc(r.name||'Resident')}</h2></div><button class="editor-close" type="button" data-close-editor>×</button></header><form id="editorForm" data-section="${section}" data-id="${esc(r.id)}"><div class="editor-grid">${f}</div><div class="editor-actions"><span class="editor-spacer"></span><button type="button" class="btn secondary" data-close-editor>Cancel</button><button class="btn primary editor-save" type="submit">Save Changes</button></div></form></section>`;document.body.appendChild(m);editorForm.onsubmit=saveEditor
}

async function saveEditor(e){
e.preventDefault();const form=e.currentTarget,section=form.dataset.section,id=form.dataset.id,r=state.rows.find(x=>String(x.id)===String(id)),v=Object.fromEntries(new FormData(form)),patch={};
if(section==='residents'){patch.living_place=text(v.living_place)||null;patch.phone=text(v.phone)||null;patch.remarks=text(v.remarks)||null}
if(section==='assign'){patch.vote_assigned_by=v.assign_status==='unassigned'?null:text(v.vote_assigned_by)||null;patch.vote_assigned_at=v.assign_status==='unassigned'?null:(r.vote_assigned_at||new Date().toISOString());patch.remarks=text(v.remarks)||null;if(v.assign_status==='completed')patch.reach_status='reached'}
if(section==='calls'){patch.phone_status=text(v.phone_status)||'need-call';patch.call_outcome=patch.phone_status;patch.call_center_agent=text(v.call_center_agent)||null;patch.call_notes=text(v.call_notes)||null;patch.last_call_at=new Date().toISOString();patch.call_attempts=Number(r.call_attempts||0)+1;if(['connected','called'].includes(patch.phone_status))patch.reach_status='reached'}
if(section==='votes'){patch.vote_status=text(v.vote_status)||'not-decided';patch.support_level=text(v.support_level)||'normal';patch.remarks=text(v.remarks)||null;if(['will-vote','not-vote'].includes(patch.vote_status)||patch.support_level==='guaranteed')patch.reach_status='reached'}
if(section==='visits'){patch.d2d_status=text(v.d2d_status)||'not-visited';patch.living_place=text(v.living_place)||null;patch.remarks=text(v.remarks)||null;if(patch.d2d_status==='reach')patch.reach_status='reached'}
if(section==='transport'){patch.transport_status=text(v.transport_status)||'not-needed';patch.remarks=text(v.remarks)||null}
if(section!=='residents')patch.phone_suggested=text(v.phone_suggested)||null;
const save=form.querySelector('.editor-save');save.disabled=true;save.textContent='Saving…';
const{data,error}=await db.from(cfg.tableName).update(patch).eq('id',id).select().single();
if(error){save.disabled=false;save.textContent='Save Changes';return alert(error.message)}
const index=state.rows.findIndex(x=>String(x.id)===String(id));if(index>=0)state.rows[index]=data;sectionEditor.remove();render()
}
function shareLink(){const link=new URL('../shared.html',location.href);link.searchParams.set('mode','self-assign');link.searchParams.set('party',state.party);link.searchParams.set('house',state.filters.address||'all');if(state.search)link.searchParams.set('search',state.search);navigator.clipboard?.writeText(link.href).then(()=>alert('Share link copied.')).catch(()=>prompt('Copy this link:',link.href))}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-editor]'))return document.getElementById('sectionEditor')?.remove();const view=e.target.closest('[data-resident-view]');if(view){state.residentView=view.dataset.residentView;state.visible=28;return render()}const edit=e.target.closest('[data-edit-id]');if(edit)return openEditor(edit.dataset.editSection,edit.dataset.editId);const nav=e.target.closest('[data-section]');if(nav){state.section=nav.dataset.section;state.filters={};state.search='';state.visible=28;location.hash=state.section;return render()}if(e.target.id==='clearFilters'){state.filters={};state.search='';state.visible=28;return render()}if(e.target.id==='loadMore'){state.visible+=28;return render()}if(e.target.id==='copyAssignmentLink')return shareLink()});
let searchTimer;
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){state.search=e.target.value;state.visible=28;clearTimeout(searchTimer);searchTimer=setTimeout(()=>render({restoreSearch:true}),180)}});
document.addEventListener('change',e=>{if(e.target.id==='globalParty'){state.party=e.target.value;state.visible=28;return render()}if(e.target.dataset.filter){state.filters[e.target.dataset.filter]=e.target.value;state.visible=28;render()}});
window.addEventListener('hashchange',()=>{const s=location.hash.slice(1);if(SECTIONS.includes(s)){state.section=s;applyPending();render()}});
window.CampaignApp={state,getRows:()=>applyParty(state.rows.slice()),getAssignments:()=>state.assignments.slice(),goToHouse:h=>{sessionStorage.setItem('campaign_prefilter_house',h);location.hash='#residents'}};
document.addEventListener('DOMContentLoaded',async()=>{if(!cfg?.supabaseUrl||!cfg?.supabaseKey||!window.supabase){adminApp.innerHTML='<main class="loading-screen"><div class="login-card"><h1>Configuration Error</h1></div></main>';return}db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const{data:{session}}=await db.auth.getSession();if(!session)return login();state.user=session.user;loadAll()});
})();
