/* MODULE: Modern Campaign Dashboard | VERSION: 1.0.0 | BUILD: 2026.07.10 */
(() => {
  'use strict';
  const cfg = window.CampaignConfig;
  if (!cfg || !window.supabase) return;
  const db = window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseKey, {auth:{persistSession:true,autoRefreshToken:true}});
  const text=v=>String(v??'').trim();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=(v,t)=>t?Math.round(v/t*100):0;
  const addr=r=>text(r.house)||text(r.living_place)||text(r.lives_in)||'No Address';
  let busy=false;
  const isDashboard=()=>!location.hash||location.hash==='#dashboard';
  async function loadRows(){const rows=[];let from=0;const size=Number(cfg.batchSize||1000);while(true){const{data,error}=await db.from(cfg.tableName).select('id,name,house,living_place,lives_in,phone,party,vote_status,reach_status,phone_status,last_call_at,d2d_status,transport_status,vote_assigned_by,vote_assigned_at,call_center_agent').order('id',{ascending:true}).range(from,from+size-1);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<size)break;from+=size;}return rows;}
  async function loadAssignments(){const{data,error}=await db.from('resident_assignments').select('resident_id,assignee_name,assigned_at').order('assigned_at',{ascending:false}).limit(250);return error?[]:(data||[]);}
  function houses(rows){const m=new Map();rows.forEach(r=>{const k=addr(r),x=m.get(k)||{name:k,total:0,assigned:0};x.total++;if(text(r.vote_assigned_by))x.assigned++;m.set(k,x)});return[...m.values()].sort((a,b)=>b.total-a.total).slice(0,8)}
  function stat(label,value,total,note,hash){const p=pct(value,total);return `<button class="md-stat" data-go="${hash}"><span>${label}</span><strong>${value.toLocaleString()}</strong><small>${note}</small><div class="md-progress"><i style="width:${p}%"></i></div><b>${p}%</b></button>`}
  function bars(items){const max=Math.max(...items.map(x=>x.value),1);return items.map(x=>`<div class="md-bar"><span>${x.label}</span><div><i style="width:${Math.round(x.value/max*100)}%"></i></div><strong>${x.value.toLocaleString()}</strong></div>`).join('')}
  function render(rows,assignments){const host=document.getElementById('pageContent');if(!host||!isDashboard())return;const total=rows.length,assigned=rows.filter(r=>text(r.vote_assigned_by)).length,called=rows.filter(r=>text(r.last_call_at)||['called','connected'].includes(text(r.phone_status))).length,visited=rows.filter(r=>text(r.d2d_status)&&text(r.d2d_status)!=='not-visited').length,reached=rows.filter(r=>text(r.reach_status)==='reached').length,willVote=rows.filter(r=>text(r.vote_status)==='will-vote').length,noPhone=rows.filter(r=>!text(r.phone)).length,unassigned=total-assigned,assignedNeverCalled=rows.filter(r=>text(r.vote_assigned_by)&&!text(r.last_call_at)).length,transportNeed=rows.filter(r=>['need','need-transport'].includes(text(r.transport_status))).length,top=houses(rows),activity=assignments.slice(0,10);
  host.innerHTML=`<section class="md-head"><div><p class="eyebrow">Campaign Command Center</p><h1>Dashboard</h1><p>Live campaign health, progress, team activity and next actions.</p></div><div class="md-tools"><input placeholder="Search name, house, party or status"><select><option>All Parties</option><option>PNC</option><option>MDP</option></select></div></section><section class="md-goal"><div><span>Today's Goal</span><strong>Contact 100 residents</strong></div><div class="md-progress"><i style="width:${Math.min(called,100)}%"></i></div><b>${Math.min(called,100)} / 100</b></section><section class="md-stats">${stat('Residents',total,total,'Master records','#residents')}${stat('Assigned',assigned,total,`${unassigned} unassigned`,'#assign')}${stat('Contacted',called,total,`${assignedNeverCalled} assigned, not called`,'#calls')}${stat('Reached',reached,total,'Confirmed contact','#calls')}${stat('Will Vote',willVote,total,'Confirmed support','#votes')}</section><section class="md-grid"><article class="md-panel"><header><span>Campaign Pipeline</span><h2>Workflow Progress</h2></header><div class="md-bars">${bars([{label:'Assigned',value:assigned},{label:'Called',value:called},{label:'Visited',value:visited},{label:'Will Vote',value:willVote}])}</div></article><article class="md-panel"><header><span>Action Centre</span><h2>Needs Attention</h2></header><div class="md-alerts"><button data-go="#assign"><b>${unassigned}</b><span>Residents unassigned</span></button><button data-go="#calls"><b>${noPhone}</b><span>Residents without phone</span></button><button data-go="#calls"><b>${assignedNeverCalled}</b><span>Assigned but never called</span></button><button data-go="#transport"><b>${transportNeed}</b><span>Need transport follow-up</span></button></div></article><article class="md-panel"><header><span>Geographic Progress</span><h2>Top Houses</h2></header><div class="md-houses">${top.map(h=>`<button data-house="${esc(h.name)}"><div><strong>${esc(h.name)}</strong><span>${h.assigned}/${h.total} assigned</span></div><div class="md-progress"><i style="width:${pct(h.assigned,h.total)}%"></i></div><b>${pct(h.assigned,h.total)}%</b></button>`).join('')}</div></article><article class="md-panel"><header><span>Recent Activity</span><h2>Assignment Feed</h2></header><div class="md-feed">${activity.length?activity.map(a=>`<div><i></i><section><strong>${esc(a.assignee_name||'Assignee')} selected a resident</strong><span>${new Date(a.assigned_at).toLocaleString('en-GB')}</span></section></div>`).join(''):'<p>No assignment activity yet.</p>'}</div></article></section><section class="md-actions"><button data-go="#residents">Residents</button><button data-go="#assign">Generate Share Link</button><button data-go="#calls">Start Calls</button><button data-go="#visits">Door to Door</button><button data-go="#votes">Vote Status</button><button data-go="#transport">Transport</button></section>`}
  async function load(){if(!isDashboard()||busy)return;const host=document.getElementById('pageContent');if(!host)return;busy=true;host.innerHTML='<div class="md-loading">Loading campaign dashboard…</div>';try{const[rows,a]=await Promise.all([loadRows(),loadAssignments()]);render(rows,a)}catch(e){host.innerHTML=`<div class="md-error">Dashboard error: ${esc(e.message)}</div>`}finally{busy=false}}
  document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){location.hash=go.dataset.go;return}const h=e.target.closest('[data-house]');if(h){sessionStorage.setItem('campaign_prefilter_house',h.dataset.house);location.hash='#residents'}});
  window.addEventListener('hashchange',()=>setTimeout(load,80));new MutationObserver(()=>{if(isDashboard()&&document.getElementById('pageContent')&&!document.querySelector('.md-head'))load()}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(load,150);
})();
