/* MODULE: Modern Campaign Dashboard | VERSION: 2.0.1 */
(() => {
'use strict';
const text=v=>String(v??'').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=(v,t)=>t?Math.round(v/t*100):0,addr=r=>text(r.house)||'No Address';
function sameDay(v,d){if(!v)return false;const x=new Date(v);return!Number.isNaN(x.getTime())&&x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()}
function topHouses(rows){const m=new Map();rows.forEach(r=>{const k=addr(r),x=m.get(k)||{name:k,total:0,assigned:0};x.total++;if(text(r.vote_assigned_by))x.assigned++;m.set(k,x)});return[...m.values()].sort((a,b)=>b.total-a.total).slice(0,8)}
function stat(label,value,total,note,hash){const p=pct(value,total);return`<button class="md-stat" data-go="${hash}"><span>${label}</span><strong>${value.toLocaleString()}</strong><small>${note}</small><div class="md-progress"><i style="width:${p}%"></i></div><b>${p}%</b></button>`}
function bars(items){const max=Math.max(...items.map(x=>x.value),1);return items.map(x=>`<div class="md-bar"><span>${x.label}</span><div><i style="width:${Math.round(x.value/max*100)}%"></i></div><strong>${x.value.toLocaleString()}</strong></div>`).join('')}
function render(){if(location.hash&&location.hash!=='#dashboard')return;const app=window.CampaignApp,host=document.getElementById('pageContent');if(!app||!host)return;const rows=app.state.rows.filter(r=>text(r.party).toUpperCase()==='PNC'),a=app.getAssignments(),today=new Date(),total=rows.length,assigned=rows.filter(r=>text(r.vote_assigned_by)).length,pending=rows.filter(r=>['pending','not-decided',''].includes(text(r.vote_status))).length,needCall=rows.filter(r=>text(r.phone_status)==='need-call').length,contacted=rows.filter(r=>text(r.last_call_at)||['called','connected'].includes(text(r.phone_status))).length,calledToday=rows.filter(r=>sameDay(r.last_call_at,today)).length,visited=rows.filter(r=>text(r.d2d_status)&&text(r.d2d_status)!=='not-visited').length,reached=rows.filter(r=>text(r.reach_status)==='reached').length,willVote=rows.filter(r=>text(r.vote_status)==='will-vote').length,noPhone=rows.filter(r=>!text(r.phone)).length,unassigned=total-assigned,assignedNeverCalled=rows.filter(r=>text(r.vote_assigned_by)&&!text(r.last_call_at)).length,transportNeed=rows.filter(r=>['need','need-transport'].includes(text(r.transport_status))).length,houses=topHouses(rows),activity=a.slice(0,10);
host.innerHTML=`<section class="md-goal"><div><span>Today's Goal</span><strong>Contact 100 residents</strong></div><div class="md-progress"><i style="width:${Math.min(calledToday,100)}%"></i></div><b>${Math.min(calledToday,100)} / 100</b></section><section class="md-stats">${stat('Total Residents',total,total,'PNC residents','#residents')}${stat('Will Vote',willVote,total,'Confirmed support','#votes')}${stat('Pending',pending,total,'Decision pending','#votes')}${stat('Need Call',needCall,total,'Call required','#calls')}${stat('Assigned',assigned,total,`${unassigned} unassigned`,'#assign')}</section><section class="md-grid"><article class="md-panel"><header><span>Campaign Pipeline</span><h2>Workflow Progress</h2></header><div class="md-bars">${bars([{label:'Assigned',value:assigned},{label:'Called',value:contacted},{label:'Visited',value:visited},{label:'Will Vote',value:willVote}])}</div></article><article class="md-panel"><header><span>Action Centre</span><h2>Needs Attention</h2></header><div class="md-alerts"><button data-go="#assign"><b>${unassigned}</b><span>Residents unassigned</span></button><button data-go="#residents"><b>${noPhone}</b><span>Residents without phone</span></button><button data-go="#calls"><b>${assignedNeverCalled}</b><span>Assigned but never called</span></button><button data-go="#transport"><b>${transportNeed}</b><span>Need transport follow-up</span></button></div></article><article class="md-panel"><header><span>Geographic Progress</span><h2>Top Houses</h2></header><div class="md-houses">${houses.map(h=>`<button data-house="${esc(h.name)}"><div><strong>${esc(h.name)}</strong><span>${h.assigned}/${h.total} assigned</span></div><div class="md-progress"><i style="width:${pct(h.assigned,h.total)}%"></i></div><b>${pct(h.assigned,h.total)}%</b></button>`).join('')}</div></article><article class="md-panel"><header><span>Recent Activity</span><h2>Assignment Feed</h2></header><div class="md-feed">${activity.length?activity.map(i=>`<div><i></i><section><strong>${esc(i.assignee_name||'Assignee')} selected a resident</strong><span>${new Date(i.assigned_at).toLocaleString('en-GB')}</span></section></div>`).join(''):'<p>No assignment activity yet.</p>'}</div></article></section>`}
document.addEventListener('campaign:dashboard',render);
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){location.hash=go.dataset.go;return}const h=e.target.closest('[data-house]');if(h&&window.CampaignApp)window.CampaignApp.goToHouse(h.dataset.house)});
})();